"""Public API for the asynchronous Ebinex client library."""

from .accounts import Account, AccountEnvironment, Balance, Profile
from .auth import Credentials, FileSessionStore, MemorySessionStore, Session, SessionStore
from .client import EbinexClient
from .config import ClientConfig
from .core import (
    AuthenticationError,
    ConnectionError,
    EbinexError,
    EventQueueOverflowError,
    NotConnectedError,
    OrderError,
    OrderRejectedError,
    OrderSubmissionUnknownError,
    ProtocolError,
    RealTradingDisabledError,
    SettlementTimeoutError,
    TransportError,
    ValidationError,
)
from .events import (
    BalanceEvent,
    BookEvent,
    BrokerTimeEvent,
    CandleEvent,
    ConnectionEvent,
    ConnectionState,
    Event,
    EventDispatcher,
    EventStream,
    HandlerToken,
    OrderEvent,
    TickerEvent,
)
from .market import Asset, BookUpdate, BrokerTime, Candle, MarketStatus, Ticker, Timeframe
from .orders import Direction, Order, OrderQuery, OrderRequest, OrderStatus, Settlement

__all__ = [
    "Account",
    "AccountEnvironment",
    "Asset",
    "AuthenticationError",
    "Balance",
    "BalanceEvent",
    "BookEvent",
    "BookUpdate",
    "BrokerTime",
    "BrokerTimeEvent",
    "Candle",
    "CandleEvent",
    "ClientConfig",
    "ConnectionError",
    "ConnectionEvent",
    "ConnectionState",
    "Credentials",
    "Direction",
    "EbinexClient",
    "EbinexError",
    "Event",
    "EventDispatcher",
    "EventQueueOverflowError",
    "EventStream",
    "FileSessionStore",
    "HandlerToken",
    "MarketStatus",
    "MemorySessionStore",
    "NotConnectedError",
    "Order",
    "OrderError",
    "OrderRejectedError",
    "OrderEvent",
    "OrderQuery",
    "OrderRequest",
    "OrderStatus",
    "OrderSubmissionUnknownError",
    "Profile",
    "ProtocolError",
    "RealTradingDisabledError",
    "Session",
    "SessionStore",
    "Settlement",
    "SettlementTimeoutError",
    "Ticker",
    "TickerEvent",
    "Timeframe",
    "TransportError",
    "ValidationError",
]

__version__ = "0.1.2"
